before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: ov+rSnjqKwjLtqTZbHAiOalpubP26CxvIiz9cR3lV0OkhAKjr61CaA5AODdEH5X9PELJwdFv6oOI9BldIAg9wzdocs+b7YIoIuZwZGDZhbp6N6bcAIvhdbjdo4XF3FMtRdgJWWzF4ShZeSyVddsotYWl563PNFBRgCCHd7kMJJtnTYxJrfmiLJPHPCXVRMb+DhegSrmfSyW3cLj1t/Il4Owtc0G7bzRCQNKIGL7TbwJuJv8wcvGqA3SzgCWi3MB4pIejYT7uCX7HTW2G0gFDw+SHOKfYe/tcrVUvAXxvsNDCAewYW/7Mus5mb4ejyyAeLf59tnPufTmaYOELVFBCe0AM+hHwB3TqEq7KEC/1P6seNJM4l15L31CUK3hiBoMClrrDz5+RtPGDI7ULgpUFKjwNhRxvgH2Rvqe1+RxqyXKPIg6rDGDTlvZiNKMx51VIO1HLd767YVo9h8XEBAoad4193IDLLx21rFKfqhU35LiOnfoUa/Dfc6UOaPj3qCAGwHIe4+wvvmaeRt9U7USAqxKU1l7SoImrKNOA/fdsMlgFj5aYPCNyTQwqsfybf1bHAJzDLggsgEua7h2mNeY7ojLDAURtyz0Cc9ZrHF8DmwXGjjK1QkcVymMbjyX32bg7dkZ9Zrcf1QaRZqTjxxrx73Lt0A/6brpDaE0mQBKD3M8= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
